version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "homeassistant"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "dependencies"
