---
# Labels names are important as they are used by Release Drafter to decide
# regarding where to record them in changelog or if to skip them.
#
# The repository labels will be automatically configured using this file and
# the GitHub Action https://github.com/marketplace/actions/github-labeler.
- name: automerge
  description: Automatically merge by Kodiak
  color: d4c5f9

- name: bug
  description: Something isn't working
  color: d73a4a

- name: dependencies
  description: Pull requests that update a dependency file
  color: 0366d6

- name: documentation
  description: Improvements or additions to documentation
  color: 0075ca

- name: duplicate
  description: This issue or pull request already exists
  color: cfd3d7

- name: feature
  description: New feature or request
  color: a2eeef

- name: github structure
  description: Pull requests that update Github actions/workflow code
  color: "000000"

- name: good first issue
  description: Good for newcomers
  color: 7057ff

- name: help wanted
  description: Extra attention is needed
  color: 008672

- name: invalid
  description: This doesn't seem right
  color: e4e669

- name: major
  description: Major changes. Used for release bump
  color: 16970B

- name: minor
  description: Minor changes. Used for release bump
  color: 16970B

- name: patch
  description: Patch changes. Used for release bump
  color: 16970B

- name: performance
  description: Performance
  color: "016175"

# Prevent Dependabot from adding version labels
- name: skip-release
  description: Skip release
  color: "000000"

- name: question
  description: Further information is requested
  color: d876e3

- name: glocaltokens
  description: For fixes related with the glocaltokens dependency
  color: 0118f0

- name: refactoring
  description: Refactoring
  color: ef67c4

- name: removal
  description: Removals and Deprecations
  color: 9ae7ea

- name: testing
  description: Testing
  color: b1fc6f

- name: wontfix
  description: This will not be worked on
  color: ffffff

- name: translation
  description: Translations
  color: eb9234

- name: wip
  description: This issue is being addressed and will be fixed ASAP. May have a linked PR.
  color: 0e8a16
